services:
  - docker
language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- lts/*
notifications:
  email:
    on_success: never
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false"
    && sh .travis/deploy_heroku.sh capture-website-api
    && sh .travis/deploy_heroku.sh capture-website-api-patching
