language: node_js
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
    - HEROKU_APP_NAME=capture-website-rest-patching
node_js:
- lts/*
notifications:
  email:
    on_success: never
after_success:
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false"
    && sh .travis/deploy_heroku.sh
