language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- lts/*
notifications:
  email:
    on_success: never
deploy:
  provider: heroku
  app:
    master: capture-website-rest-patching
  api_key:
    secure: Uf9T71S96bClTp7eh8YfkQXmuyd99QseocP3Wa+tmCE09q1cRI/b/cTU5w8hUOvrzwzBQ3P4ZqklTKnrM4vwLKJfPazLAP0IC92nLX/9zIk7eT1PA6Eo5jxtUwWRYniAcfX/ew/CgGzulfCOpcTtKEVd7w8w+KWoyBi7reYQjrYUVHh0dalO0ex/kld7/KaXR1R7w+D/z/K/0NFrWSxdL7MJwTEHgm3zqpnL+Sy3oEhIb277Ee41NJucTG0pRztODyALxLTG36xsoOBDDDFWizBQvXYsfwuYCsaw2PdYaTcEGAuy1zNcvn8nAXtbi9qowCZbinrySe3aEYvZkVf0AH25tC6isyQriaJEKS0f9XA6uUVdwZrwhlwpQjuS242SIJdHy0eN4VYp83MgwG7mKhG5E2ujB6cSJMpxj6GwSwetGDmGIUvYRnZwEcHl7yDqUxerDC8UqUuLSMpeCyY9gMq0bO6o93/EbAHNkho2g3itSl1PFd6vuM9GS4g1962pA4hum1tCcAI0pBYNdzdV1D1vqZPj+EQVp6VcoC+0bvjoXdyIK/GYmP037LF0wzv7znZ87Ud9+vigitRn5h4xKlx4G6E+J49gL1P8Y68iswMqZJ8WME8H8wDisFWwswXL833VEPZBAKwPZ6irEASMRwUOClAHZfB68KscoH2k2cM=
